using System;
using System.Collections.Generic;

namespace PhaseHeist;

/// <summary>
/// 轻量双语本地化。所有 UI 文本经 Loc.T / Loc.TF 获取；
/// 切换语言后触发 LanguageChanged，各界面自行重建文本。
/// </summary>
public static class Loc
{
    public static event Action? LanguageChanged;

    public static string Language { get; private set; } = "zh";

    public static void SetLanguage(string code)
    {
        code = code == "en" ? "en" : "zh";
        if (Language == code)
        {
            return;
        }

        Language = code;
        LanguageChanged?.Invoke();
    }

    public static string T(string key)
    {
        var table = Language == "en" ? En : Zh;
        return table.TryGetValue(key, out string? value) ? value : key;
    }

    public static string TF(string key, params object[] args)
    {
        return string.Format(T(key), args);
    }

    private static readonly Dictionary<string, string> Zh = new()
    {
        // 主菜单
        ["menu.title"] = "银行劫案",
        ["menu.subtitle"] = "潜入 · 谈判 · 突入 · 撤离",
        ["menu.solo"] = "单人开始",
        ["menu.multiplayer"] = "多人联机",
        ["menu.settings"] = "设置",
        ["menu.quit"] = "退出游戏",
        ["menu.version"] = "原型版本 0.4 · Godot 4.6 C#",

        // 联机页
        ["mp.title"] = "多人联机",
        ["mp.name"] = "玩家名字",
        ["mp.address"] = "服务器地址",
        ["mp.port"] = "端口",
        ["mp.host"] = "创建房间 (Host)",
        ["mp.join"] = "加入房间 (Join)",
        ["mp.back"] = "返回",
        ["mp.hint"] = "局域网/公网直连，UDP。主机即服务端。",

        // 设置页
        ["set.title"] = "设置",
        ["set.language"] = "语言 / Language",
        ["set.sensitivity"] = "鼠标灵敏度",
        ["set.master"] = "主音量",
        ["set.voice"] = "语音音量",
        ["set.voicemode"] = "语音模式",
        ["set.voicemode.off"] = "关闭麦克风",
        ["set.voicemode.ptt"] = "按 V 说话",
        ["set.voicemode.open"] = "自由开麦",
        ["set.fullscreen"] = "全屏",
        ["set.back"] = "返回",

        // 阵营选择
        ["team.title"] = "选择阵营",
        ["team.robber"] = "劫匪",
        ["team.police"] = "警察",
        ["team.robber.desc"] = "混入人群、锁门谈判、抢金库、侧门或下水道撤离",
        ["team.police.desc"] = "观察喝退、喇叭谈判、解锁后突入、堵撤离路线",

        // HUD
        ["hud.brand"] = "BANK HEIST",
        ["hud.phase.init"] = "初始化",
        ["hud.street"] = "街面渗透：劫匪混入人群，警察只能喝退",
        ["hud.countdown"] = "倒计时 {0}  突入 {1}",
        ["hud.breach.ok"] = "允许",
        ["hud.breach.no"] = "封锁中",
        ["hud.health"] = "生命",
        ["hud.breachbar"] = "突入解锁",
        ["hud.timebar"] = "倒计时",
        ["hud.tactical"] = "战术态势",
        ["hud.team.none"] = "阵营未选择",
        ["hud.gun"] = "持枪",
        ["hud.nogun"] = "无枪",
        ["hud.outside"] = "外线",
        ["hud.fakehostage"] = "伪装成人质",
        ["hud.disguise"] = "伪装 {0}",
        ["hud.loot.taken"] = "金库目标已取得",
        ["hud.loot.not"] = "金库目标未取得",
        ["hud.route.side"] = "警方堵点: 侧门",
        ["hud.route.sewer"] = "警方堵点: 下水道",
        ["hud.route.none"] = "警方堵点: 未部署",
        ["hud.hostages"] = "人质 {0} 留存 / {1} 释放 / {2} 死亡",
        ["hud.hostage.short"] = "人质 {0}",
        ["hud.loot.short.taken"] = "目标 已取",
        ["hud.loot.short.not"] = "目标 未取",
        ["hud.score"] = "警察 {0} | 劫匪 {1}",
        ["hud.phase.label"] = "阶段: {0}",
        ["hud.speaking"] = "● 正在说话",
        ["hud.voice.ptt"] = "V 说话",
        ["hud.hint.move"] = "WASD 移动",
        ["hud.hint.sprint"] = "Shift 冲刺",
        ["hud.hint.interact"] = "E 交互",
        ["hud.hint.context"] = "F/Q 动作",
        ["hud.hint.fire"] = "LMB 射击",
        ["hud.hint.menu"] = "ESC 菜单",

        // ESC 菜单
        ["esc.title"] = "战术菜单",
        ["esc.resume"] = "继续游戏",
        ["esc.settings"] = "设置",
        ["esc.reselect"] = "重新选择阵营",
        ["esc.mainmenu"] = "返回主菜单",
        ["esc.quit"] = "退出游戏",
        ["esc.stats"] = "阶段: {0}\n{1} / HP {2} / {3}\n{4}",

        // 结算
        ["settlement.title"] = "回合结算",
        ["settlement.robberwin"] = "劫案成功 · 劫匪胜",
        ["settlement.policewin"] = "劫案失败 · 警方胜",
        ["settlement.body"] = "警察 {0} 分  ·  劫匪 {1} 分\n人质：{2} 存活 / {3} 释放 / {4} 死亡\n目标：{5}\n撤离堵点：{6}",
        ["settlement.close"] = "继续观察",

        // 载具
        ["obj.drive"] = "驾驶载具 [E]",
        ["hud.exitcar"] = "下车",
        ["hud.kmh"] = "{0} km/h",

        // 阶段名
        ["phase.street"] = "街面渗透",
        ["phase.lockdown"] = "锁门",
        ["phase.negotiation"] = "谈判",
        ["phase.assault"] = "突入",
        ["phase.escape"] = "逃离",
        ["phase.scored"] = "劫匪成功",
        ["phase.failed"] = "劫匪失败",

        // 名牌
        ["tag.you"] = "(你)",
        ["tag.arrested"] = " 已捕",
        ["tag.loot"] = " [目标]",
        ["tag.fake"] = " 伪人质",

        // 交互点
        ["obj.enterbank"] = "混入银行并关闭大门 [E]",
        ["obj.disguise"] = "换装混入人群 [E/F]",
        ["obj.shout"] = "警察喝退可疑人员 [E/F]",
        ["obj.phone"] = "劫匪电话谈判 [E]",
        ["obj.megaphone"] = "警察喇叭谈判 [E/F]",
        ["obj.vault"] = "抢金库目标 [E]",
        ["obj.release"] = "释放人质 [E]",
        ["obj.kill"] = "杀死人质 [E]",
        ["obj.fake"] = "伪装成人质 [E/F]",
        ["obj.record"] = "录音伪装 [E/F]",
        ["obj.entryfront"] = "前门突入 [E]",
        ["obj.entryside"] = "侧门突入 [E]",
        ["obj.entryback"] = "后门突入 [E]",
        ["obj.blockside"] = "警察堵侧门 [E]",
        ["obj.blocksewer"] = "警察堵下水道 [E]",
        ["obj.escapeside"] = "劫匪侧门撤离 [E]",
        ["obj.escapesewer"] = "劫匪钻入下水道 [E]",

        // 地图标注
        ["map.bank"] = "第一国民银行",
        ["map.hall"] = "营业大厅",
        ["map.vault"] = "金库",
        ["map.offices"] = "办公区",
        ["map.server"] = "安防机房",
        ["map.hostage"] = "人质等候区",
        ["map.plaza"] = "银行前广场 / 人群",
        ["map.policeline"] = "警戒线",
        ["map.parking"] = "停车场",
        ["map.sideexit"] = "侧巷撤离线",
        ["map.sewer"] = "下水道入口",
        ["map.street"] = "中央大街",

        // NPC
        ["npc.civilian"] = "路人",
        ["npc.hostage"] = "人质",
        ["npc.released"] = "已释放",
        ["npc.dead"] = "死亡",
        ["door.open"] = "银行大门: 开启",
        ["door.closed"] = "银行大门: 已关闭",
        ["door.vault"] = "金库门",

        // 状态广播
        ["st.solo"] = "单人模式",
        ["st.hosting"] = "已创建房间 UDP {0}",
        ["st.connecting"] = "连接中 {0}:{1}",
        ["st.connected"] = "已连接，编号 {0}",
        ["st.hostfail"] = "创建房间失败 ({0})",
        ["st.joinfail"] = "加入失败 ({0})",
        ["st.connfail"] = "连接失败",
        ["st.serverlost"] = "与服务器断开",
        ["st.peerjoin"] = "玩家 {0} 加入",
        ["st.peerleft"] = "玩家 {0} 离开",
        ["st.team.robber"] = "阵营: 劫匪",
        ["st.team.police"] = "阵营: 警察",
        ["st.enterbank"] = "劫匪混入银行，大门关闭，10 分钟倒计时开始",
        ["st.enterbank.denied"] = "只有劫匪能在封锁前混入银行",
        ["st.disguise"] = "劫匪换装完成，伪装等级 {0}",
        ["st.disguise.denied"] = "只有封锁前的劫匪能换装",
        ["st.shout.hit"] = "警察喝退 P{0}，劫匪可换装后再次尝试",
        ["st.shout.none"] = "警察没有发现可疑劫匪",
        ["st.shout.denied"] = "只有封锁前的警察能喝退",
        ["st.negotiate.locked"] = "大门关闭后才能谈判",
        ["st.negotiate.police"] = "警察使用喇叭谈判",
        ["st.negotiate.robber"] = "劫匪使用电话回应谈判",
        ["st.vault.taken"] = "金库目标已取得，可从侧门或下水道撤离",
        ["st.vault.denied"] = "只有锁门后的劫匪能抢金库",
        ["st.host.release"] = "劫匪释放一名人质，警察评分上升",
        ["st.host.release.none"] = "没有可释放的人质",
        ["st.host.kill"] = "人质死亡，警察最终评分下降",
        ["st.host.kill.none"] = "没有可处理的人质",
        ["st.host.denied"] = "只有锁门后的劫匪能处理人质",
        ["st.fake.done"] = "劫匪伪装成人质",
        ["st.fake.denied"] = "只有锁门后的劫匪能伪装人质",
        ["st.record.done"] = "劫匪准备录音伪装",
        ["st.record.denied"] = "只有锁门后的劫匪能准备录音",
        ["st.entry.denied"] = "只有警察能选择突入路线",
        ["st.entry.early"] = "倒计时达到 30% 后警察才能突入",
        ["st.entry.pushed.front"] = "警察前门突入被劫匪发现，被迫退回",
        ["st.entry.pushed.side"] = "警察侧门突入被劫匪发现，被迫退回",
        ["st.entry.pushed.back"] = "警察后门突入被劫匪发现，被迫退回",
        ["st.entry.ok.front"] = "警察从前门静默突入",
        ["st.entry.ok.side"] = "警察从侧门静默突入",
        ["st.entry.ok.back"] = "警察从后门静默突入",
        ["st.block.side"] = "警察开始堵侧门撤离路线",
        ["st.block.sewer"] = "警察开始堵下水道撤离路线",
        ["st.block.denied"] = "只有警察能堵撤离路线",
        ["st.escape.needloot"] = "劫匪必须先取得金库目标才能撤离",
        ["st.escape.arrested"] = "劫匪撞上堵点且无武器，被逮捕",
        ["st.escape.side"] = "劫匪从侧门撤离成功",
        ["st.escape.sewer"] = "劫匪从下水道撤离成功",
        ["st.escape.side.broke"] = "劫匪强行突破侧门堵点撤离",
        ["st.escape.sewer.broke"] = "劫匪强行突破下水道堵点撤离",
        ["st.unknown"] = "未知行为",
        ["st.shout.cd"] = "喝退冷却中",
        ["st.negotiate.cd"] = "谈判通道冷却中",
        ["st.arrest.player"] = "P{0} 被逮捕，警方 +{1} 分",
        ["st.kill.robber"] = "劫匪 P{0} 被击倒",
        ["st.kill.police"] = "警察 P{0} 被击倒",

        // 交互提示 / 结算
        ["hud.interact"] = "[E] {0}",
        ["result.win"] = "劫案成功",
        ["result.fail"] = "劫案失败",
        ["result.score"] = "警察 {0} 分  ·  劫匪 {1} 分",
        ["result.hostages"] = "人质：{0} 存活 / {1} 释放 / {2} 死亡",
        ["result.menu"] = "返回主菜单",
        ["result.again"] = "重选阵营继续",
        ["result.quit"] = "退出游戏",
    };

    private static readonly Dictionary<string, string> En = new()
    {
        ["menu.title"] = "BANK HEIST",
        ["menu.subtitle"] = "Infiltrate · Negotiate · Breach · Escape",
        ["menu.solo"] = "Play Solo",
        ["menu.multiplayer"] = "Multiplayer",
        ["menu.settings"] = "Settings",
        ["menu.quit"] = "Quit",
        ["menu.version"] = "Prototype 0.4 · Godot 4.6 C#",

        ["mp.title"] = "Multiplayer",
        ["mp.name"] = "Player Name",
        ["mp.address"] = "Server Address",
        ["mp.port"] = "Port",
        ["mp.host"] = "Host Game",
        ["mp.join"] = "Join Game",
        ["mp.back"] = "Back",
        ["mp.hint"] = "Direct UDP connection. Host acts as server.",

        ["set.title"] = "Settings",
        ["set.language"] = "Language / 语言",
        ["set.sensitivity"] = "Mouse Sensitivity",
        ["set.master"] = "Master Volume",
        ["set.voice"] = "Voice Volume",
        ["set.voicemode"] = "Voice Mode",
        ["set.voicemode.off"] = "Microphone Off",
        ["set.voicemode.ptt"] = "Push To Talk (V)",
        ["set.voicemode.open"] = "Open Mic",
        ["set.fullscreen"] = "Fullscreen",
        ["set.back"] = "Back",

        ["team.title"] = "Choose Team",
        ["team.robber"] = "Robber",
        ["team.police"] = "Police",
        ["team.robber.desc"] = "Blend in, lock down, loot the vault, escape via side door or sewer",
        ["team.police.desc"] = "Observe, shout down, negotiate, breach after unlock, block exits",

        ["hud.brand"] = "BANK HEIST",
        ["hud.phase.init"] = "Initializing",
        ["hud.street"] = "Street phase: robbers blend in, police may only shout down",
        ["hud.countdown"] = "Timer {0}  Breach {1}",
        ["hud.breach.ok"] = "ALLOWED",
        ["hud.breach.no"] = "LOCKED",
        ["hud.health"] = "Health",
        ["hud.breachbar"] = "Breach Unlock",
        ["hud.timebar"] = "Countdown",
        ["hud.tactical"] = "Tactical Status",
        ["hud.team.none"] = "No team",
        ["hud.gun"] = "Armed",
        ["hud.nogun"] = "Unarmed",
        ["hud.outside"] = "Perimeter",
        ["hud.fakehostage"] = "Posing as hostage",
        ["hud.disguise"] = "Disguise {0}",
        ["hud.loot.taken"] = "Vault loot secured",
        ["hud.loot.not"] = "Vault loot not taken",
        ["hud.route.side"] = "Police block: side door",
        ["hud.route.sewer"] = "Police block: sewer",
        ["hud.route.none"] = "Police block: none",
        ["hud.hostages"] = "Hostages {0} held / {1} released / {2} dead",
        ["hud.hostage.short"] = "Hostages {0}",
        ["hud.loot.short.taken"] = "Loot OK",
        ["hud.loot.short.not"] = "No loot",
        ["hud.score"] = "Police {0} | Robbers {1}",
        ["hud.phase.label"] = "Phase: {0}",
        ["hud.speaking"] = "● Speaking",
        ["hud.voice.ptt"] = "V Talk",
        ["hud.hint.move"] = "WASD Move",
        ["hud.hint.sprint"] = "Shift Sprint",
        ["hud.hint.interact"] = "E Interact",
        ["hud.hint.context"] = "F/Q Action",
        ["hud.hint.fire"] = "LMB Fire",
        ["hud.hint.menu"] = "ESC Menu",

        ["esc.title"] = "Tactical Menu",
        ["esc.resume"] = "Resume",
        ["esc.settings"] = "Settings",
        ["esc.reselect"] = "Reselect Team",
        ["esc.mainmenu"] = "Main Menu",
        ["esc.quit"] = "Quit Game",
        ["esc.stats"] = "Phase: {0}\n{1} / HP {2} / {3}\n{4}",

        ["settlement.title"] = "Round Result",
        ["settlement.robberwin"] = "Heist Complete · Robbers Win",
        ["settlement.policewin"] = "Heist Failed · Police Win",
        ["settlement.body"] = "Police {0}  ·  Robbers {1}\nHostages: {2} alive / {3} released / {4} dead\nObjective: {5}\nPolice block: {6}",
        ["settlement.close"] = "Keep Watching",

        ["obj.drive"] = "Drive vehicle [E]",
        ["hud.exitcar"] = "Exit vehicle",
        ["hud.kmh"] = "{0} km/h",

        ["phase.street"] = "Street",
        ["phase.lockdown"] = "Lockdown",
        ["phase.negotiation"] = "Negotiation",
        ["phase.assault"] = "Assault",
        ["phase.escape"] = "Escape",
        ["phase.scored"] = "Robbers Win",
        ["phase.failed"] = "Robbers Fail",

        ["tag.you"] = "(You)",
        ["tag.arrested"] = " ARRESTED",
        ["tag.loot"] = " [LOOT]",
        ["tag.fake"] = " FakeHostage",

        ["obj.enterbank"] = "Enter bank & lock doors [E]",
        ["obj.disguise"] = "Change disguise [E/F]",
        ["obj.shout"] = "Shout down suspect [E/F]",
        ["obj.phone"] = "Robber phone negotiation [E]",
        ["obj.megaphone"] = "Police megaphone [E/F]",
        ["obj.vault"] = "Grab vault loot [E]",
        ["obj.release"] = "Release hostage [E]",
        ["obj.kill"] = "Kill hostage [E]",
        ["obj.fake"] = "Pose as hostage [E/F]",
        ["obj.record"] = "Prepare recording [E/F]",
        ["obj.entryfront"] = "Breach front door [E]",
        ["obj.entryside"] = "Breach side door [E]",
        ["obj.entryback"] = "Breach back door [E]",
        ["obj.blockside"] = "Block side exit [E]",
        ["obj.blocksewer"] = "Block sewer exit [E]",
        ["obj.escapeside"] = "Escape via side door [E]",
        ["obj.escapesewer"] = "Escape via sewer [E]",

        ["map.bank"] = "FIRST NATIONAL BANK",
        ["map.hall"] = "Banking Hall",
        ["map.vault"] = "Vault",
        ["map.offices"] = "Offices",
        ["map.server"] = "Security Room",
        ["map.hostage"] = "Waiting Area",
        ["map.plaza"] = "Bank Plaza / Crowd",
        ["map.policeline"] = "Police Line",
        ["map.parking"] = "Parking Lot",
        ["map.sideexit"] = "Side Alley Escape",
        ["map.sewer"] = "Sewer Access",
        ["map.street"] = "Main Street",

        ["npc.civilian"] = "Civilian",
        ["npc.hostage"] = "Hostage",
        ["npc.released"] = "Released",
        ["npc.dead"] = "Dead",
        ["door.open"] = "Main Door: OPEN",
        ["door.closed"] = "Main Door: LOCKED",
        ["door.vault"] = "Vault Door",

        ["st.solo"] = "Solo mode",
        ["st.hosting"] = "Hosting on UDP {0}",
        ["st.connecting"] = "Connecting {0}:{1}",
        ["st.connected"] = "Connected as peer {0}",
        ["st.hostfail"] = "Host failed ({0})",
        ["st.joinfail"] = "Join failed ({0})",
        ["st.connfail"] = "Connection failed",
        ["st.serverlost"] = "Server disconnected",
        ["st.peerjoin"] = "Player {0} joined",
        ["st.peerleft"] = "Player {0} left",
        ["st.team.robber"] = "Team: Robber",
        ["st.team.police"] = "Team: Police",
        ["st.enterbank"] = "Robber slipped inside; doors locked, 10-minute timer started",
        ["st.enterbank.denied"] = "Only robbers can enter before lockdown",
        ["st.disguise"] = "Disguise changed, level {0}",
        ["st.disguise.denied"] = "Only pre-lockdown robbers can change disguise",
        ["st.shout.hit"] = "Police shouted down P{0}; robber may retry after disguise",
        ["st.shout.none"] = "Police found no suspicious robber",
        ["st.shout.denied"] = "Only pre-lockdown police can shout down",
        ["st.negotiate.locked"] = "Negotiation opens after lockdown",
        ["st.negotiate.police"] = "Police negotiate by megaphone",
        ["st.negotiate.robber"] = "Robbers respond by phone",
        ["st.vault.taken"] = "Vault loot secured; escape via side door or sewer",
        ["st.vault.denied"] = "Only post-lockdown robbers can loot the vault",
        ["st.host.release"] = "Hostage released; police score up",
        ["st.host.release.none"] = "No hostage to release",
        ["st.host.kill"] = "Hostage killed; police final score drops",
        ["st.host.kill.none"] = "No hostage available",
        ["st.host.denied"] = "Only post-lockdown robbers can handle hostages",
        ["st.fake.done"] = "Robber now posing as hostage",
        ["st.fake.denied"] = "Only post-lockdown robbers can pose as hostage",
        ["st.record.done"] = "Recording prepared",
        ["st.record.denied"] = "Only post-lockdown robbers can prepare recordings",
        ["st.entry.denied"] = "Only police can breach",
        ["st.entry.early"] = "Breach unlocks after 30% of the timer",
        ["st.entry.pushed.front"] = "Front breach spotted; police pushed back",
        ["st.entry.pushed.side"] = "Side breach spotted; police pushed back",
        ["st.entry.pushed.back"] = "Back breach spotted; police pushed back",
        ["st.entry.ok.front"] = "Police breached the front door",
        ["st.entry.ok.side"] = "Police breached the side door",
        ["st.entry.ok.back"] = "Police breached the back door",
        ["st.block.side"] = "Police now blocking the side exit",
        ["st.block.sewer"] = "Police now blocking the sewer exit",
        ["st.block.denied"] = "Only police can block exits",
        ["st.escape.needloot"] = "Robbers must take the vault loot first",
        ["st.escape.arrested"] = "Unarmed robber hit a police block; arrested",
        ["st.escape.side"] = "Robber escaped via the side door",
        ["st.escape.sewer"] = "Robber escaped via the sewer",
        ["st.escape.side.broke"] = "Robber forced through the side-door block",
        ["st.escape.sewer.broke"] = "Robber forced through the sewer block",
        ["st.unknown"] = "Unknown action",
        ["st.shout.cd"] = "Shout-down on cooldown",
        ["st.negotiate.cd"] = "Negotiation channel on cooldown",
        ["st.arrest.player"] = "P{0} arrested, police +{1}",
        ["st.kill.robber"] = "Robber P{0} downed",
        ["st.kill.police"] = "Police P{0} downed",

        ["hud.interact"] = "[E] {0}",
        ["result.win"] = "HEIST COMPLETE",
        ["result.fail"] = "HEIST FAILED",
        ["result.score"] = "Police {0}  ·  Robbers {1}",
        ["result.hostages"] = "Hostages: {0} alive / {1} released / {2} dead",
        ["result.menu"] = "Main Menu",
        ["result.again"] = "Reselect Team",
        ["result.quit"] = "Quit Game",
    };
}
